export const HARDCODED_FOLLOWERS = [
  "StrawHat_22", "Benery", "AnimeVibe", "NeonNinja99", "CyberPunk_X", "StarGazer", "VoidWalker22",
  "QuantumLeap", "EchoBlade", "PixelKing", "LunarMoon", "SolarFlare", "CosmicDust", "NightRider",
  "DayWalker", "DreamChaser", "StormBringer", "ShadowMonarch", "CrimsonWarrior", "AzureMage",
  "GoldenRogue", "SilverHunter", "IronSlayer", "SteelKnight", "CrystalPaladin", "DiamondBerserker",
  "RubySorcerer", "SapphireWarlock", "EmeraldDruid", "JadeShaman", "OnyxPriest", "ObsidianCleric",
  "EpicMonk", "LegendaryBard", "MythicThief", "DivineAssassin", "CelestialMercenary", "GalacticBounty",
  "UniversalSniper", "InfiniteScout", "EternalPilot", "ImmortalCaptain", "StrawHat_Ninja", "NeonPunk",
  "CyberGamer", "StarLover", "VoidGazer", "QuantumWalker", "EchoLeap", "PixelBlade", "LunarKing",
  "SolarMoon", "CosmicFlare", "NightDust", "DayRider", "DreamChaser", "StormBringer", "ShadowMonarch",
  "CrimsonWarrior", "AzureMage", "GoldenRogue", "SilverHunter", "IronSlayer", "SteelKnight",
  "CrystalPaladin", "DiamondBerserker", "RubySorcerer", "SapphireWarlock", "EmeraldDruid", "JadeShaman",
  "OnyxPriest", "ObsidianCleric", "EpicMonk", "LegendaryBard", "MythicThief", "DivineAssassin",
  "CelestialMercenary", "GalacticBounty", "UniversalSniper", "InfiniteScout", "EternalPilot", "ImmortalCaptain",
  "Ninja_22", "Punk_99", "Gamer_X", "Lover_22", "Gazer_99", "Walker_X", "Leap_22", "Blade_99",
  "King_X", "Moon_22", "Flare_99", "Dust_X", "Rider_22", "Chaser_99", "Bringer_X", "Monarch_22",
  "Warrior_99", "Mage_X", "Rogue_22", "Hunter_99", "Slayer_X", "Knight_22", "Paladin_99", "Berserker_X",
  "Sorcerer_22", "Warlock_99", "Druid_X", "Shaman_22", "Priest_99", "Cleric_X", "Monk_22", "Bard_99",
  "Thief_X", "Assassin_22", "Mercenary_99", "Bounty_X", "Sniper_22", "Scout_99", "Pilot_X", "Captain_22",
  "StrawHatNinja99", "NeonPunkX", "CyberGamer22", "StarLover99", "VoidGazerX", "QuantumWalker22",
  "EchoLeap99", "PixelBladeX", "LunarKing22", "SolarMoon99", "CosmicFlareX", "NightDust22",
  "DayRider99", "DreamChaserX", "StormBringer22", "ShadowMonarch99", "CrimsonWarriorX", "AzureMage22",
  "GoldenRogue99", "SilverHunterX", "IronSlayer22", "SteelKnight99", "CrystalPaladinX", "DiamondBerserker22",
  "RubySorcerer99", "SapphireWarlockX", "EmeraldDruid22", "JadeShaman99", "OnyxPriestX", "ObsidianCleric22",
  "EpicMonk99", "LegendaryBardX", "MythicThief22", "DivineAssassin99", "CelestialMercenaryX", "GalacticBounty22",
  "UniversalSniper99", "InfiniteScoutX", "EternalPilot22", "ImmortalCaptain99",
  "SuperGamer", "UltraNoob", "ProPlayer", "SneakySniper", "LoudMouth", "QuietNinja", "HappyCamper",
  "SadPanda", "AngryBird", "CrazyCat", "LazyDog", "WildWolf", "BraveLion", "FastCheetah", "SlowTurtle",
  "SmartOwl", "DumbFox", "FunnyMonkey", "SeriousBear", "CoolPenguin", "HotDragon", "ColdIce",
  "WarmFire", "BrightLight", "DarkShadow", "GoodBoy", "BadGirl", "HeroZero", "ZeroHero", "AlphaWolf",
  "BetaCat", "GammaDog", "DeltaBird", "EpsilonFish", "ZetaBug", "EtaAnt", "ThetaBee", "IotaFly"
];
